version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.13.2
    working_directory: ~/repo
    environment:
      CI: false
    resource_class: large
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "32:c3:da:fa:f4:14:e0:88:92:ed:6c:36:22:ad:44:c3"
      - run: ssh-keyscan ${SERVER_IP} >> ~/.ssh/known_hosts
      - run:
          name: "Clean Upload folder"
          command: ssh ${SERVER_USER}@${SERVER_IP} "rm -rf /var/www/gbar/upload/*"
      - run:
          name: "Build UI & SERVER"
          command: |
            cd erp-ui
            npm install
            npm run build
            scp -r build ${SERVER_USER}@${SERVER_IP}:/var/www/gbar/upload/ui
            
            cd ../server
            npm install
            npm run build
            touch dist/.env
            echo "DB_HOST=${DB_HOST}" >> dist/.env
            echo "DB_USERNAME=${DB_USERNAME}" >> dist/.env
            echo "DB_PASSWORD=${DB_PASSWORD}" >> dist/.env
            echo "DB_DATABASE=${DB_DATABASE}" >> dist/.env

            scp -r dist ${SERVER_USER}@${SERVER_IP}:/var/www/gbar.digitize.ee/upload/server
#      - run:
#          name: "Execute deploy script"
#          command: ssh ${SERVER_USER}@${SERVER_IP} 'bash -s < /var/www/gbar/deploy.sh'

workflows:
  deploy:
    jobs:
      - build:
          context:
            - test
          filters:
            branches:
              only:
                - main
