name: Deploy-Process
on:
  push:
    tags:
    - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Get tag name
      uses: olegtarasov/get-tag@v2
    
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: server/dist
        remote: var/www/gbar.digitize.ee/test
        host: 167.71.39.235
        username: root
        privateKey: ${{ PRIVATE_KEY }}
