name: Deploy-Process
on:
  push:
    tags:
    - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Test
      run: echo ${{ secrets.PRIVATE_KEY }}
    
    - name: Deploy file
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
          username: root
          server: 167.71.39.235
          port: 22
          local_path: './server/dist/*'
          remote_path: '/gbar.digitize.ee/test'
          sftp_only: true
          password: 123QweAs
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
